### ISSUE TITLE
File server does not start

### ISSUE THREAD

**Issue by Thorgrim901** [atlassian/nucleus#74]
Hi, i'm using this docker image with docker-compose:
`version: '3'                                      
                                                  
services:                                         
  redis:                                          
    container_name: redis                         
    hostname: redis                               
    image: redis                                  
    ports:                                        
      - "6379:6379"                               
                                                  
  nucleus:                                        
    image: atlassian/nucleus                      
    depends_on:                                   
      - redis                                     
    volumes:                                      
      - './config.js:/opt/service/config.js'      
      - './files:/opt/service/.files'             
      - './db:/opt/service/db'                    
    ports:                                        
      - 8888:8888                                 
      - 9999:9999                                 
    environment:                                  
      - DEBUG=nucleus*                            `

in my config.js i have:
`const path = require('path');

module.exports = {
  port: 8888,
  baseURL: 'http://192.168.0.203:8888',
  dbStrategy: 'sequelize',
  sequelize: {
    dialect: 'sqlite',
    storage: path.resolve(__dirname, 'db', 'db.sqlite'),
  },
  fileStrategy: 'local',
  local: {
    root: path.resolve(__dirname, '.files'),
    staticUrl: 'http://192.168.0.203:9999'
  },
  authStrategy: 'local',
  localAuth: [{
    displayName: 'Administrator',
    username: 'admin',
    password: '*hidden*',
    photo: 'https://pbs.twimg.com/profile_images/1219364727/charlie-support_400x400.png'
  }],
  adminIdentifiers: ['admin'],
  sessionConfig: {
    type: "redis",
    secret: 'ThisIsNotSecret',

    redis: {
      host: 'redis',
      port: '6379'
    }
  },
  organization: 'org',
  gpgSigningKey: `*hidden*`,
  defaultRollout: 0
};`
where 192.168.0.203 is the ip of the machine

everithing works except the file server. On port 9999 nothing is running.

Thanks

**Comment by Wolvan** [comment]
Look at this https://github.com/atlassian/nucleus/issues/42#issuecomment-404531251 and the following comments

**Comment by b-zurg** [comment]
This is a working configuration if you want to use docker-compose with the docker image. 
Keep in mind I made this **only for development**.  For production I wouldn't use a container-scoped postgres image but rather an RDS or other instance or set up the postgres image to persist data storage somewhere else.  

However it does work nicely for development purposes and allows you to test the update flow: 

```yaml
## run "docker-compose up --remove-orphans" in the directory with this file.
version: '3'                                      
                                                  
services:
  apache:
    container_name: httpd
    image: "httpd:latest"
    ports:
      - 9999:80
    volumes:
      - ./.files:/usr/local/apache2/htdocs/
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
  redis:
    container_name: redis
    hostname: redis
    depends_on:
      - db
    image: redis
    ports:
      - 6379:6379
  nucleus:
    image: atlassian/nucleus
    depends_on:
      - redis
      - db
      - apache
    ports:
      - 3030:3030
      - 8888:8888
    environment:
      - DEBUG=nucleus*
      - NODE_ENV=production
    volumes:
      - ./config.js:/opt/service/config.js
      - ./.files:/opt/service/.files/
```

Since the docker image runs the production script it doesn't run the local file server - which makes sense.  All this does is uses an apache httpd server to serve files and mounts the location it expects to a local folder, as well as the location that nucleus is configured for storing files to the same local folder.  

Pretty nifty!
